baseURL = "https://quill.codes/"
languageCode = "en-us"
title = "Quill.Codes"
googleAnalytics = "UA-117840360-6"
theme = "quill-codes"

[taxonomies]
  tag = "tags"
  series = "series"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4

[params]
  owner = "Casey"
  description = "Worthwhile articles, tips, and freelance advice from Casey McQuillan, a freelance cloud software engineer."
  email = "Casey@quilltechnologies.com"
  logo_svg = "/images/blog_icon.svg"
  profile_photo = "/images/profile.png"
  profile_alt = "Picture of Casey (Quill)"
  env = "production"
  github = "cmcquillan"
  twitter = "QuillCodes"
  linkedin = "caseymcquillan"
  recent_posts_number = 6
  main_sections = [ "posts" ]
  sub_sections = [ "tips" ]
