# Netlify config

# Redirects
[[redirects]]
  from = "/apps/fiddle/templates/*"
  to = "/apps/fiddle/index.html"
  status = 200
  force = true

# Special headers
[[headers]]

  for = "/*"
  
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' syndication.twitter.com; style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com; font-src cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' syndication.twitter.com platform.twitter.com www.googletagmanager.com; report-uri https://quilltech.report-uri.com/r/d/csp/wizard ; frame-src 'self' platform.twitter.com; report-to csp-endpoint;"
    Report-To = '{ "group": "csp-endpoint", "max_age": 10886400, "endpoints": [ { "url": "https://quilltech.report-uri.com/r/d/csp/wizard" }] }, {"group":"default","max_age":31536000,"endpoints":[{"url":"https://quilltech.report-uri.com/a/d/g"}],"include_subdomains":true}'
    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
