name: Publish Github Pages

# On Push
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Github Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Debug PWD
      run: ls -Al
    - name: Build script
      run: ./publish_to_pages.sh
